enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = false
build-mode = "module"
excluded-patches = "'Copy video URL' 'Downloads' 'Announcements' 'Enable debugging'"
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"


[TickTick ]
apkmirror-dlurl = "https://www.apkmirror.com/apk/ticktick-limited/ticktick-to-do-list-with-reminder-day-planner/"
uptodown-dlurl = "https://ticktick.en.uptodown.com/android/"
patches-source = "YeahItsMeAgain/revanced-patches"
cli-source = "ReVanced/revanced-cli"
included-patches = "'Unlock premium' 'Hide ads'"
arch = "arm64-v8a"
version = "latest"

