enable-magisk-update = true

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
included-patches = "'Remove player controls background'"
excluded-patches = "'Announcements' 'Enable debugging' 'External downloads' 'Copy video URL' 'Enable tablet layout' 'Tablet mini player' 'Hide player buttons'"

[Lightroom]
enabled = true
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
excluded-patches = "'Disable mandatory login'"
arch = "arm64-v8a"

[Photos]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
included-patches = "'Spoof features' 'GmsCore support'"
arch = "both"
