logging-to-file = false        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

[YouTube]
app-name = "Youtube"
build-mode = "both"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Remove player controls background'"
excluded-patches = "'External downloads'"
module-prop-name = "YT-Revanced-Magisk"

[Music]
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-arch = "both"

[Lightroom]
app-name = "Lightroom"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
apkmirror-arch = "arm64-v8a"

