enable-magisk-update = true
[Youtube Revanced]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
included-patches = "remove-player-controls-background"
excluded-patches = "custom-branding premium-heading"


[YouTube-Extended Advanced] 
enabled = false
app-name = "YouTube"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "YT-Advanced/revanced-cli"
rv-brand = "ReVanced Extended X"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
