
logging-to-file = false        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
included-patches = "'Remove player controls background'"
excluded-patches = "'Tablet mini player' 'Premium heading' 'Enable tablet layout'  'External downloads' 'Enable debugging' 'Announcements'"