enable-magisk-update = true

[YouTube]
apkmirror-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

build-mode = "module"
included-patches = "'Remove player controls background'"
excluded-patches = "'Tablet mini player' 'Premium heading' 'Enable tablet layout'  'External downloads' 'Enable debugging' 'Announcements'"