enable-magisk-update = true
[Youtube Revanced]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
included-patches = "remove-player-controls-background"
excluded-patches = "custom-branding premium-heading"

[YT Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"
build-mode = "both"
