enable-magisk-update = true

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Copy video URL' 'Downloads' 'Announcements' 'Enable debugging'"
build-mode = "module"
version = "auto"

[TickTick ]
apkmirror-dlurl = "https://www.apkmirror.com/apk/ticktick-limited/"
patches-source = "YeahItsMeAgain/revanced-patches"
arch = "arm64-v8a"
version = "latest"
